# Generated by Django 4.1.7 on 2023-03-04 18:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import market.validators
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=100000)])),
                ('brand', models.CharField(max_length=300)),
                ('model', models.CharField(max_length=300)),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('price', models.FloatField(validators=[market.validators.validate_price])),
                ('decription', tinymce.models.HTMLField(default='')),
                ('screen_size', models.CharField(max_length=100)),
                ('disk_size', models.IntegerField()),
                ('cpu', models.CharField(max_length=300)),
                ('gpu', models.CharField(max_length=300)),
                ('ram_memory', models.IntegerField()),
                ('os', models.CharField(max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
