# Generated by Django 4.1.7 on 2023-03-06 14:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='cpu',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='decription',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='disk_size',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='gpu',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='os',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram_memory',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screen_size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
