# Generated by Django 4.1.7 on 2023-03-06 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_category_image_alter_laptop_cpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='product_no',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(limit_value=10000)]),
        ),
    ]
