# Generated by Django 4.1.7 on 2023-03-06 16:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_laptop_count_alter_laptop_product_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=6)])),
            ],
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='product_no',
        ),
        migrations.AddField(
            model_name='laptop',
            name='product_code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='market.product_code', to_field='product_code'),
            preserve_default=False,
        ),
    ]
