# Generated by Django 4.1.7 on 2023-03-11 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_product_code_remove_laptop_product_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='id',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='product_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='market.product_code', to_field='product_code'),
        ),
    ]
