# Generated by Django 4.1.7 on 2023-03-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_order_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_items',
            old_name='order_id',
            new_name='order',
        ),
    ]
