# Generated by Django 4.1.7 on 2023-03-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_television_desktop'),
    ]

    operations = [
        migrations.AddField(
            model_name='television',
            name='screen_size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
