# Generated by Django 4.1.7 on 2023-03-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_television_screen_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desktop',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='television',
            old_name='decription',
            new_name='description',
        ),
    ]
